export const EMOTES = [
  "akward_kid",
  "amongus_twerk",
  "arab_dance",
  "ban",
  "bonk_cat",
  "bruh_mike",
  "cat_confused",
  "cat_knife",
  "cat_nooo",
  "catto_cry",
  "clap",
  "confused_wat",
  "cooked",
  "cut_eggplant",
  "cute_cat",
  "dance",
  "doggo_dance",
  "doggo_kek",
  "duck_tweaking",
  "eyes_shaking",
  "facepalm",
  "finger_no_wave",
  "fire",
  "flooshed",
  "fuck",
  "gay",
  "gg",
  "glazing",
  "gru_what",
  "kekw",
  "kekw_pointing",
  "kermit_shoot",
  "lel_harold",
  "macho_frog",
  "not_stonks",
  "ooo",
  "pensive_animated",
  "pepe_clown",
  "pepe_cool",
  "pepe_jam",
  "pepe_juice",
  "pepe_king",
  "pepe_lmfaoo",
  "pepe_no",
  "pepe_popcorn",
  "pepe_shocked",
  "pepe_vroom",
  "pog",
  "pug_dance",
  "roblox_dance",
  "roblox_man_face",
  "rofl",
  "sadcat",
  "sexy_face",
  "shy",
  "smoke",
  "spongebob_idc",
  "spunkboi",
  "steve",
  "stonks",
  "suck",
  "swag_cat",
  "thonk",
  "troll",
  "when_imposter_sus",
  "wide_putin",
] as const;

export type EmoteName = (typeof EMOTES)[number];

export const EMOTE_SET = new Set<string>(EMOTES);

export function emoteSrc(name: string) {
  return `/img/emotes/${name}.png`;
}
