#!/usr/bin/env python3
"""Themed display names — Diceblox-style punchy titles, original wording."""

from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]

NAMES = {
    "oil-baron": "Black Gold",
    "optimus": "Prime Core",
    "bank-vault": "Locked Vault",
    "prestige": "High Society",
    "ascension": "Skybound",
    "evil-fantasy": "Dark Fable",
    "everest": "Summit",
    "billionaire": "Ultra Rich",
    "eclipse": "Dark Sun",
    "wealth": "Loaded",
    "life-changing": "Life Alter",
    "imagination": "Daydream",
    "green-machine": "Emerald Engine",
    "shiny-collection": "Gleam Set",
    "ancient-relics": "Lost Relics",
    "dominus-collector": "Hood Archive",
    "diamonds": "Cut Gems",
    "batman": "Night Knight",
    "rich-desires": "Gilded Want",
    "lord-federation": "Crown League",
    "millionaire": "Seven Figures",
    "2-percent-astra": "Astra Odds",
    "valkyrie-vision": "Valk Sight",
    "fortune": "Jackpot Run",
    "miami-life": "Neon Coast",
    "tango-dancer": "Last Dance",
    "high-demand": "Hot List",
    "bloodbath": "Crimson Tide",
    "lucky-drop": "Lucky Pull",
    "vineyard-vibes": "Vintage",
    "crimson-wrath": "Scarlet Rage",
    "roulette": "Spin Room",
    "10-percent-sapphire": "Sapphire Odds",
    "cursed-dream": "Hexed Sleep",
    "20-percent-baller": "Baller Odds",
    "shaggy": "Rainbow Mop",
    "expensive-flip": "High Flip",
    "ro-roller": "Roblox Roll",
    "10-percent-federation": "Fed Odds",
    "golden-galore": "Gold Rush",
    "artifical-intelligence": "Neural Pack",
    "tix-bonanza": "Ticket Storm",
    "dominus-flip": "Hood Flip",
    "deluxe-horns": "Horn Stack",
    "kings-crowns": "Royal Caps",
    "irregular": "Odd One",
    "jazzy": "Night Jazz",
    "10-percent-gold": "Gold Odds",
    "10-percent-dominus": "Hood Odds",
    "money-printer": "Print Shop",
    "black-or-white": "Mono Mix",
    "north-pole-riches": "Polar Loot",
    "barbenheimer": "Pink Blast",
    "tomb-raider": "Tomb Run",
    "red-dawn": "Scarlet Rise",
    "traders-delight": "Trade Floor",
    "ice-cold": "Frostbite",
    "hi-lo-roller": "High Low",
    "skateboard-days": "Deck Days",
    "white-gold": "Pale Gold",
    "opportunist": "Quick Grab",
    "void-star-ice": "Frozen Void",
    "valk-flip": "Valk Swap",
    "fedora-fiasco": "Fedora Frenzy",
    "vampire": "Night Fang",
    "eyes-of-aura": "Aura Gaze",
    "indigo": "Deep Indigo",
    "sword-heights": "Blade Peak",
    "temple-of-wealth": "Gold Temple",
    "steampunk-booster": "Brass Boost",
    "black-pearl": "Dark Pearl",
    "10-percent-bling": "Bling Odds",
    "eros": "Heartshot",
    "gold-dream": "Gilded Sleep",
    "balloon-juicer": "Balloon Pop",
    "online-dater": "Profile Pic",
    "space-blue": "Orbit Blue",
    "30-percent-domnio": "Domino Odds",
    "dark-ice": "Black Ice",
    "facelift": "Fresh Face",
    "highlight-boom": "Highlight Hit",
    "immortality": "Endless",
    "10-percent-yum": "Yum Odds",
    "bucket-box": "Bucket Run",
    "lord-of-war": "War Crown",
    "beast-case": "Wild Pack",
    "star-juicer": "Star Press",
    "hanz-lair": "Lair Drop",
    "linkmons-case": "Linkmon Pack",
    "fedora-hunt": "Fedora Hunt",
    "duck-duck-goose": "Duck Hunt",
    "favorite-tunes": "Mix Tape",
    "periastron-flip": "Star Sword",
    "10-percent-hell": "Hell Odds",
    "buckberry": "Berry Bucks",
    "demonic-dream": "Demon Sleep",
    "icebox": "Chill Box",
    "rgb-roulette": "RGB Spin",
    "electronics": "Wired",
    "sparkler": "Spark Pack",
    "crown-case": "Crown Room",
    "federation-case": "Fed Hall",
    "imperialist": "Empire",
    "dark-lord": "Shadow Lord",
    "purple-plasma": "Violet Arc",
    "arctic-wonderland": "Frozen Fair",
    "take-flight": "Liftoff",
    "treasure-case": "Booty Box",
    "ultimate-headphones": "Max Cans",
    "valkyries-ascension": "Valk Rise",
    "crystal-case": "Crystal Cut",
    "3-percent-horns": "Horn Odds",
    "grape-galore": "Grape Crush",
    "mafia-moves": "Made Man",
    "dream-box": "Soft Dream",
    "5-percent-tentacles": "Tentacle Odds",
    "blue-addiction": "Blue Fix",
    "10-percent-sshf": "Sparkle Odds",
    "10-percent-capwn": "Cap Odds",
    "pets-party": "Pet Parade",
    "tsunami": "Wave Crash",
    "red-reign": "Red Rule",
    "plushies": "Plush Pit",
    "crazy-boom": "Wild Boom",
    "barbie-girl": "Pink World",
    "green-bonanza": "Green Pay",
    "sphinxs-riddles": "Sand Riddle",
    "jingle-jackpot": "Jingle Hit",
    "summer-splash": "Heat Wave",
    "electric-juicer": "Volt Press",
    "santas-sleigh": "Sleigh Run",
    "dragon-warrior": "Dragon Scale",
    "ice-storm": "Hailstorm",
    "hoodlum": "Street Hood",
    "gingerbread-jackpot": "Cookie Hit",
    "15-percent-bang": "Bang Odds",
    "black-iron-case": "Iron Dark",
    "diamond-fit": "Diamond Fit",
    "antler-mania": "Antler Run",
    "ice-dream": "Frost Dream",
    "sunken-secrets": "Deep Secret",
    "ghastly-ghouls": "Grave Hour",
    "greenfest": "Green Fest",
    "10-percent-silver": "Silver Odds",
    "emperious": "Empyrean",
    "30-percent-galaxy": "Galaxy Odds",
    "noob-juicer": "Noob Press",
    "volcanic-blaze": "Magma Run",
    "red-lagoon": "Red Pool",
    "levs-15-percent": "Lev Odds",
    "dominus-descents": "Hood Fall",
    "bombastic-boom": "Big Boom",
    "colorful-extensions": "Color Ends",
    "new-years-flip": "New Year Flip",
    "hooded": "Cloaked",
    "baller": "Big Shot",
    "hellfire": "Inferno",
    "award-show": "Red Carpet",
    "crowns-of-the-night": "Night Crowns",
    "sunglass-express": "Shade Run",
    "blizzard-bundle": "Snow Pack",
    "police-juicer": "Badge Press",
    "wild-wanwood": "Wanwood Wild",
    "vamp-punk": "Fang Punk",
    "10-percent-snowman": "Snow Odds",
    "commando-case": "Raid Pack",
    "pumpkin-patrol": "Pumpkin Watch",
    "halloween-bash": "Haunt Night",
    "e-girl-heaven": "Soft Core",
    "zeus-case": "Thunder Pack",
    "american-patriot": "Stars Stripes",
    "samurai-sake": "Blade Sip",
    "sparkle-stockpile": "Sparkle Stash",
    "dark-desire": "Dark Want",
    "shaggy-flip": "Mop Flip",
    "super-smiles": "Big Grin",
    "hair-deluxe": "Hair Stack",
    "azure-addiction": "Azure Fix",
    "deck-the-halls": "Hall Deck",
    "bluesteel-case": "Blue Steel",
    "discord-moderator": "Mod Pack",
    "10-percent-tooth": "Tooth Odds",
    "5-percent-prayer": "Prayer Odds",
    "golden-case": "Gold Box",
    "lottery-ticket": "Scratcher",
    "doge-dream": "Doge Sleep",
    "top-hat-galore": "Top Hat Run",
    "toxic-waste": "Biohazard",
    "lights-out": "Blackout",
    "epicness": "Epic Drop",
    "gold-mine": "Gold Vein",
    "pirate-plunder": "Pirate Take",
    "horns": "Horn Pit",
    "1-percent-yum": "Rare Yum",
    "bubble-trouble": "Bubble Pop",
    "bow-tie-bonanza": "Bow Tie Run",
    "industrial-case": "Factory",
    "classic-case": "OG Pack",
    "atlantis": "Deep City",
    "6-percent-beast": "Beast Odds",
    "federation-dream": "Fed Dream",
    "headless-express": "Headless Run",
    "festive-fortune": "Festive Hit",
    "paradise-payday": "Island Pay",
    "200x-duchess": "Duchess Odds",
    "hatbot-havoc": "Hatbot Chaos",
    "1-percent-emerald": "Rare Emerald",
    "red-delight": "Red Sweet",
    "10-percent-dream": "Dream Odds",
    "overseer-case": "Overseer",
    "beautiful-hair": "Hair Glow",
    "gaelic-luck": "Clover Hit",
    "sunburst-surprise": "Sunburst",
    "galactic-win": "Galaxy Win",
    "blackout-bang": "Black Bang",
    "roblots": "Bot Drop",
    "dancing-fruits": "Fruit Dance",
    "silver-vs-gold": "Silver Gold",
    "kungfu-case": "Dojo Pack",
    "3-percent-violet": "Violet Odds",
    "lolfiesta": "Fiesta",
    "frosty-case": "Frost Pack",
    "polar-prestige": "Polar Class",
    "tropical-treasure": "Tropic Loot",
    "book-case": "Page Pack",
    "grim-or-pilgrim": "Grim Pick",
    "white-bandz": "White Stack",
    "50-percent-legit": "Coin Flip",
    "adurite-case": "Adurite",
    "all-the-santas": "Santa Stack",
    "hearty-breakfast": "Breakfast",
    "viking-case": "Longship",
    "diy-case": "Workshop",
    "10-percent-juiced": "Juice Odds",
    "blox-depot": "Depot",
    "sinister-mystery": "Sinister",
    "blade-arsenal": "Blade Rack",
    "love-you": "Heart Pack",
    "8-bit-case": "Pixel Pack",
    "dark-deception": "Dark Trick",
    "10-percent-virtual": "Virtual Odds",
    "lucky-case": "Lucky Box",
    "party-rock": "Party Pack",
    "yellowmania": "Yellow Rush",
    "the-1-percent": "Elite One",
    "holiday-haul": "Holiday Run",
    "sunny-stockpile": "Sun Stash",
    "brilliant-boom": "Shine Boom",
    "praefectus-dream": "Prefect Dream",
    "eye-of-the-prince": "Prince Eye",
    "headwear-havoc": "Hat Chaos",
    "egg-case": "Egg Hunt",
    "budget-flip": "Cheap Flip",
    "heads-or-glasses": "Heads Specs",
    "zoo-case": "Zoo Drop",
    "good-luck": "Lucky Charm",
    "shoot-for-the-stars": "Star Shot",
    "turning-the-tides": "Tide Turn",
    "50-50": "Even Odds",
    "cheesy": "Cheese Run",
    "beach-bonanza": "Shore Loot",
    "stocking-surprise": "Stocking",
    "budget-spins": "Cheap Spin",
    "low-baller": "Low Roll",
    "courageous-comeback": "Comeback",
    "cheap-box": "Penny Pack",
}


def main() -> None:
    names = list(NAMES.values())
    dups = {n for n in names if names.count(n) > 1}
    if dups:
        raise SystemExit(f"duplicate names: {dups}")

    for rel in ("src/lib/cases-data.json", "server/data/cases-data.json"):
        path = ROOT / rel
        data = json.loads(path.read_text())
        missing = []
        for row in data:
            slug = row["slug"]
            if slug in NAMES:
                row["name"] = NAMES[slug]
            else:
                missing.append(slug)
        path.write_text(json.dumps(data, indent=2) + "\n")
        print(path.name, "updated", len(data), "missing", missing)


if __name__ == "__main__":
    main()
